void router();
void private_segment(float start_x, float start_y, float end_x, float end_y);
void private_segment_colors(const Line_point& point, bool open);
void private_endpoint();
void private_rotation();
void private_normal();
void private_connect();
void private_geometry();
void private_quad(float ax, float ay, float bx, float by, float u0, float u1);
void private_dashed();
void private_gradient();
void private_single_color();
void private_fill_inside();
void private_fill_outside();
void private_band_spans(float top, float bottom, std::vector<std::array<float, 2>>& out) const;
void private_crossings(float y, std::vector<float>& out) const;
int private_pixel_col(float x) const;
void private_pixel_rect(int first_col, int last_col, int row, const std::array<uint8_t, 3>& color, float alpha);
void private_pixel_cells(const std::array<std::array<float, 2>, 4>& corner, float u0, float u1);
void private_edge_pick(bool& mode, float size);
void private_edge_place();
void private_edge_cap();
void private_edge_triangle(const std::array<std::array<float, 2>, 4>& corner);
void private_round_path();
