Vulkan_viewport viewport;
Vulkan_surface surface;
Vulkan_swapchain swapchain;
Vulkan_renderpass renderpass;
Vulkan_framebuffer framebuffer;
Vulkan_command_pool command_pool;
Vulkan_command_buffer command_buffer;
Vulkan_synchronization synchronization;
