Vulkan_viewport viewport;
uint32_t *pending_width, *pending_height;
SDL_Window** id;
bool initialized{false};
Vulkan_surface surface;
Vulkan_command_pool command_pool;
bool rebuild_flag{false};
Vulkan_swapchain swapchain;
Vulkan_renderpass renderpass;
Vulkan_framebuffer framebuffer;
Vulkan_command_buffer command_buffer;
Vulkan_synchronization synchronization;