Window& setting();
Window& setting(Window_settings_info window_settings_info);
Window& create();
Window& create(Window_create_info& Window_create_info);
Window& position_adjustment_numerical(float x, float y);
Window& position_adjustment_numerical(int x, int y);
Window& position_adjustment_positional(int x, int y);
Window& resize();
Window& resize(int w, int h);
Window& resize(float w, float h);
Window& run();
Window& close();