uint8_t display_index{0};  
uint32_t width{0}, height{0};
uint32_t logic_width{1600};
uint32_t logic_height{900};
float aspectratio{0};
std::string icon;
std::string name{"a window"};
SDL_Window* id{nullptr};
bool isrun{true};
Window_time time;
window_mouse mouse;
Key_board key;
//Window_vulkan window_vulkan;
